Add: mariadb running verification

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,6 +48,22 @@ jobs:
         composer --version
         which composer
 
+    - name: Start MariaDB service
+      run: |
+        sudo service mysql start
+        for i in {1..10}; do
+          if sudo mysqladmin ping --silent; then
+            echo "MariaDB is up and running!";
+            break;
+          fi;
+          echo "Waiting for MariaDB to start... ($i/10)";
+          sleep 3;
+        done
+        if ! sudo mysqladmin ping --silent; then
+          echo "MariaDB failed to start.";
+          exit 1;
+        fi
+
     - name: Prepare database
       run: |
         sudo mysql -e "CREATE USER IF NOT EXISTS 'test'@'%' IDENTIFIED BY 'test';"
